version: "3.9"
services:

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025"
      - "8025"
    expose:
      - 8025
    networks:
      - my_network

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    networks:
      - my_network

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-flask-app
    expose:
      - 5000
    depends_on:
      - mongodb
      - mailhog
    networks:
      - my_network

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - flask-app
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
